-- Test Users
INSERT INTO users (
    user_id, first_name, last_name, email, height_cm, date_of_birth, city,
    education_level, gender, occupation, bio,
    profile_status, elo_score, trusted_badge, good_experience_badge, verified_photos,
    profile_completeness, coordinates_longitude, coordinates_latitude,
    role, photo_validation_status,
    preferred_language, spoken_languages, spoken_languages_display,
    date_intentions, date_intentions_display,
    relationship_type, relationship_type_display,
    kids_preference, kids_preference_display,
    sexual_orientation, sexual_orientation_display,
    ethnicity, ethnicity_display,
    interests, traits
) VALUES
(
    'test-user-123',
    'John',
    'Doe',
    'john.doe@test.com',
    180,
    '1990-01-15',
    'London',
    'UNIVERSITY',
    'MALE',
    'Software Engineer',
    'Test user for development',
    'ACTIVE',
    1200,
    false,
    false,
    false,
    50,
    -0.102,
    51.503,
    'USER',
    'VALIDATED',
    'ENGLISH',
    ARRAY['ENGLISH', 'SPANISH'],
    false,
    'SERIOUS_DATING',
    false,
    'MONOGAMOUS',
    false,
    'OPEN_TO_KIDS',
    false,
    'STRAIGHT',
    false,
    ARRAY['BLACK_AFRICAN_DESCENT'],
    false,
    ARRAY['HIKING', 'CODING', 'READING', 'TRAVEL', 'PHOTOGRAPHY'],
    ARRAY['AMBITIOUS', 'CREATIVE', 'EMPATHETIC']
),
(
    'test-user-456',
    'Jane',
    'Smith',
    'jane.smith@test.com',
    165,
    '1992-05-20',
    'Manchester',
    'MASTERS',
    'FEMALE',
    'Product Manager',
    'Another test user',
    'ACTIVE',
    1150,
    true,
    false,
    false,
    75,
    -2.2426,
    53.4808,
    'USER',
    'VALIDATED',
    'ENGLISH',
    ARRAY['ENGLISH', 'FRENCH'],
    true,
    'RELATIONSHIP',
    true,
    'MONOGAMOUS',
    true,
    'OPEN_TO_KIDS',
    true,
    'STRAIGHT',
    false,
    ARRAY['WHITE_BRITISH'],
    false,
    ARRAY['YOGA', 'COOKING', 'MUSIC', 'ART', 'WINE'],
    ARRAY['COMPASSIONATE', 'ORGANIZED', 'ADVENTUROUS']
),
(
    'firebase-uid-test-1',
    'Test',
    'Premium',
    'premium@test.com',
    175,
    '1988-12-10',
    'Birmingham',
    'PHD',
    'NON_BINARY',
    'Researcher',
    'Premium test account',
    'PREMIUM',
    1500,
    true,
    true,
    true,
    90,
    -1.8904,
    52.4862,
    'USER',
    'VALIDATED',
    'ENGLISH',
    ARRAY['ENGLISH'],
    true,
    'CASUAL',
    true,
    'OPEN',
    false,
    'NO_KIDS',
    false,
    'BISEXUAL',
    true,
    ARRAY['MIXED'],
    false,
    ARRAY['GAMING', 'TECH', 'MOVIES', 'CONCERTS', 'COFFEE'],
    ARRAY['ANALYTICAL', 'INTROVERTED', 'CURIOUS', 'LOYAL']
)
ON CONFLICT (user_id) DO NOTHING;

-- Test Wallets
INSERT INTO wallets (user_id, token_balance, lifetime_spent, lifetime_purchased, currency)
VALUES
    ('test-user-123', 0, 0, 0, 'GBP'),
    ('test-user-456', 100, 50, 150, 'GBP'),
    ('firebase-uid-test-1', 500, 200, 700, 'GBP');